import { Categoria } from "./productos/entities/categoria";
import { Especie } from "./productos/entities/especie";
import { Producto } from "./productos/entities/producto";
import { Subcategoria } from "./productos/entities/subcategoria";
import { Peluqueria } from './servicios/entities/peluqueria';
import { Comuna } from "./ubicacion/entities/comuna";
import { Usuario } from "./usuarios/entities/usuario";

export const SOLICITUDES_CONTACTO = [];

export const COMUNAS : Comuna[] = [
  new Comuna(1, "Colina"),
  new Comuna(2, "Lampa"),
  new Comuna(3, "Til Til"),
  new Comuna(4, "Pirque"),
  new Comuna(5, "Puente Alto"),
  new Comuna(6, "San José de Maipo"),
  new Comuna(7, "Buin"),
  new Comuna(8, "Calera de Tango"),
  new Comuna(9, "Paine"),
  new Comuna(10, "San Bernardo"),
  new Comuna(11, "Alhué"),
  new Comuna(12, "Curacaví"),
  new Comuna(13, "María Pinto"),
  new Comuna(14, "Melipilla"),
  new Comuna(15, "San Pedro"),
  new Comuna(16, "Cerrillos"),
  new Comuna(17, "Cerro Navia"),
  new Comuna(18, "Conchalí"),
  new Comuna(19, "El Bosque"),
  new Comuna(20, "Estación Central"),
  new Comuna(21, "Huechuraba"),
  new Comuna(22, "Independencia"),
  new Comuna(23, "La Cisterna"),
  new Comuna(24, "La Granja"),
  new Comuna(25, "La Florida"),
  new Comuna(26, "La Pintana"),
  new Comuna(27, "La Reina"),
  new Comuna(28, "Las Condes"),
  new Comuna(29, "Lo Barnechea"),
  new Comuna(30, "Lo Espejo"),
  new Comuna(31, "Lo Prado"),
  new Comuna(32, "Macul"),
  new Comuna(33, "Maipú"),
  new Comuna(34, "Ñuñoa"),
  new Comuna(35, "Pedro Aguirre Cerda"),
  new Comuna(36, "Peñalolén"),
  new Comuna(37, "Providencia"),
  new Comuna(38, "Pudahuel"),
  new Comuna(39, "Quilicura"),
  new Comuna(40, "Quinta Normal"),
  new Comuna(41, "Recoleta"),
  new Comuna(42, "Renca"),
  new Comuna(43, "San Miguel"),
  new Comuna(44, "San Joaquín"),
  new Comuna(45, "San Ramón"),
  new Comuna(46, "Santiago"),
  new Comuna(47, "Vitacura"),
  new Comuna(48, "El Monte"),
  new Comuna(49, "Isla de Maipo"),
  new Comuna(50, "Padre Hurtado"),
  new Comuna(51, "Peñaflor"),
  new Comuna(52, "Talagante")
];

export const PELUQUERIAS = [
  new Peluqueria(100, 10, "Peludos y Pomposos"),
  new Peluqueria(99, 24, "Estilo Canino"),
  new Peluqueria(98, 29, "Patas y Plumas Spa"),
  new Peluqueria(97, 10, "Elegancia Cuatro Patas"),
  new Peluqueria(96, 25, "Peluquería Guau-Guau"),
  new Peluqueria(95, 8, "Pawsitively Posh"),
  new Peluqueria(94, 4, "Estética MiauMiau"),
  new Peluqueria(93, 20, "Pet Glamour Studio"),
  new Peluqueria(92, 48, "Colas Felices"),
  new Peluqueria(91, 15, "Perros y Peines"),
  new Peluqueria(90, 43, "Canine Chic"),
  new Peluqueria(89, 17, "Furry Fashion"),
  new Peluqueria(88, 43, "Pelos y Bigotes"),
  new Peluqueria(87, 26, "El Ángel Peludo"),
  new Peluqueria(86, 4, "Pet Beauty Salon"),
  new Peluqueria(85, 11, "Estilo y Patitas"),
  new Peluqueria(84, 31, "Gatos y Lazos"),
  new Peluqueria(83, 36, "Doggy Style Salón"),
  new Peluqueria(82, 42, "Peluquería Cola de Sirena"),
  new Peluqueria(81, 33, "Paws and Claws Spa"),
  new Peluqueria(80, 11, "Peluquería Animal Fashion"),
  new Peluqueria(79, 46, "Cuatro Patas Elegantes"),
  new Peluqueria(78, 39, "Tail Waggers"),
  new Peluqueria(77, 14, "Peluquería Canina Chic"),
  new Peluqueria(76, 40, "Amigos Brillantes"),
  new Peluqueria(75, 48, "Grooming Woof"),
  new Peluqueria(74, 18, "Estilo Perruno"),
  new Peluqueria(73, 24, "Pet Paradise Salon"),
  new Peluqueria(72, 1, "Patas Glamurosas"),
  new Peluqueria(71, 23, "Huellas y Cortes"),
  new Peluqueria(70, 1, "El Corte Perfecto"),
  new Peluqueria(69, 34, "Peluquería Mascota Moderna"),
  new Peluqueria(68, 45, "Patitas con Estilo"),
  new Peluqueria(67, 46, "Doggy Divas"),
  new Peluqueria(66, 40, "Estética Peluche"),
  new Peluqueria(65, 31, "Pet Hair Affair"),
  new Peluqueria(64, 15, "Canine Crown"),
  new Peluqueria(63, 36, "Mascotas con Estilo"),
  new Peluqueria(62, 2, "Fashion Furs"),
  new Peluqueria(61, 23, "Peluquería Pet Elegance"),
  new Peluqueria(60, 1, "Corte Canino Cool"),
  new Peluqueria(59, 6, "Spa de Mascotas Chic"),
  new Peluqueria(58, 17, "Estilo Animal"),
  new Peluqueria(57, 1, "Glamour Paws"),
  new Peluqueria(56, 20, "Salón de Belleza Pet"),
  new Peluqueria(55, 32, "Animal Allure"),
  new Peluqueria(54, 14, "Peluquería Woofy"),
  new Peluqueria(53, 43, "Trendy Tails"),
  new Peluqueria(52, 12, "Mascotas Metro"),
  new Peluqueria(51, 10, "Bella Mascota"),
  new Peluqueria(50, 1, "Estética Cuatro Patas"),
  new Peluqueria(49, 21, "Cortes Caninos"),
  new Peluqueria(48, 22, "Salón de Belleza Peludo"),
  new Peluqueria(47, 42, "Doggy Divas y Dandies"),
  new Peluqueria(46, 4, "The Furry Fab"),
  new Peluqueria(45, 43, "Peluquería Perros y Gatos"),
  new Peluqueria(44, 2, "Mascota Chic"),
  new Peluqueria(43, 2, "Estilo Furry"),
  new Peluqueria(42, 41, "Pet Glitz"),
  new Peluqueria(41, 21, "Elegancia Peluda"),
  new Peluqueria(40, 33, "Animal Elegance"),
  new Peluqueria(39, 40, "Peluquería Glamour Paw"),
  new Peluqueria(38, 31, "Canine Elegance"),
  new Peluqueria(37, 44, "Pet Style Studio"),
  new Peluqueria(36, 5, "Amor Peludo"),
  new Peluqueria(35, 45, "Mascotas Majestuosas"),
  new Peluqueria(34, 14, "El Corte de Peluche"),
  new Peluqueria(33, 1, "Spa Animal"),
  new Peluqueria(32, 45, "Huellas y Cortes Fashions"),
  new Peluqueria(31, 30, "Mascota Mágica"),
  new Peluqueria(30, 23, "Grooming Glam"),
  new Peluqueria(29, 36, "Elegancia Animal"),
  new Peluqueria(28, 48, "Peluquería Perro Chic"),
  new Peluqueria(27, 7, "Pet Elegance"),
  new Peluqueria(26, 34, "Salón de Belleza Canino"),
  new Peluqueria(25, 46, "Tailor Tails"),
  new Peluqueria(24, 26, "Patas de Peluche"),
  new Peluqueria(23, 22, "Woof Walk-In"),
  new Peluqueria(22, 19, "Estética Pawsitiva"),
  new Peluqueria(21, 27, "Mascotas con Glamour"),
  new Peluqueria(20, 40, "Animal Chic"),
  new Peluqueria(19, 36, "Cortes de Cola"),
  new Peluqueria(18, 15, "Peluquería Pet Chic"),
  new Peluqueria(17, 17, "Pet Palace Grooming"),
  new Peluqueria(16, 8, "Estilo Perruno Chic"),
  new Peluqueria(15, 32, "Furry Fashionistas"),
  new Peluqueria(14, 20, "Gato Glam"),
  new Peluqueria(13, 20, "Pawsome Grooming"),
  new Peluqueria(12, 29, "Mascotas y Estilos"),
  new Peluqueria(11, 1, "Belleza Animal"),
  new Peluqueria(10, 33, "Pet Prestige"),
  new Peluqueria(9, 27, "Estética de Lujo"),
  new Peluqueria(8, 10, "Diva Dog Salon"),
  new Peluqueria(7, 22, "Canino Glamour"),
  new Peluqueria(6, 31, "Peluquería Elegancia Animal"),
  new Peluqueria(5, 28, "Paws and Relax"),
  new Peluqueria(4, 49, "Perros y Pintas"),
  new Peluqueria(3, 44, "Salón de Belleza Pet Chic"),
  new Peluqueria(2, 1, "Estilo Elegante"),
  new Peluqueria(1, 22, "Peluquería Mascota Mágica")
];

export const USUARIOS : Usuario[] = [
  new Usuario("11111111-1", "juan.perez@example.com", "a123456", "Juan Pérez", "912345678"),
  new Usuario("22222222-2", "maria.lopez@fakemail.com", "b123456", "María López", "911223344"),
  new Usuario("12345678-5", "carlos.garcia@norealmail.net", "c123456", "Carlos García", "955554444"),
  new Usuario("11222333-9", "ana.martinez@dummyemail.org", "d123456", "Ana María Martínez", "955556666")
];

export const ESPECIES: Especie[] = [
  new Especie("PERRO", "Perro"),
  new Especie("GATO", "Gato"),
  new Especie("AVE", "Ave"),
  new Especie("ROEDOR", "Roedor"),
  new Especie("REPTIL", "Reptil"),
  new Especie("PEZ", "Pez"),
];

export const CATEGORIAS : Categoria[] = [
  new Categoria("ACCESORIOS", "Accesorios"),
  new Categoria("ALIMENTACION", "Alimentación")
];

export const SUBCATEGORIAS : Subcategoria[] = [
  new Subcategoria("VESTUARIO", "Vestuario y accesorios", "ACCESORIOS"),
  new Subcategoria("JUGUETES", "Juguetes", "ACCESORIOS"),
  new Subcategoria("TRANSPORTE", "Transporte y seguridad", "ACCESORIOS"),
  new Subcategoria("ALIMENTO", "Alimento", "ALIMENTACION"),
];

export const PRODUCTOS : Producto[] = [
  new Producto(1, "NutriPellets Premium para Perros",                       "ALIMENTACION", "ALIMENTO", "PERRO",   10800, 20, "/productos/1.png"),
  new Producto(2, "GatoGourmet Delicias de Salmón",                         "ALIMENTACION", "ALIMENTO", "GATO",    12500, 10, "/productos/2.png"),
  new Producto(3, "AvesFestín Mezcla de Semillas",                          "ALIMENTACION", "ALIMENTO", "AVE",     25500, 11, "/productos/3.png"),
  new Producto(4, "RoedorYummies Bloques Nutritivos",                       "ALIMENTACION", "ALIMENTO", "ROEDOR",  55800, 25, "/productos/4.png"),
  new Producto(5, "FiestaFish Copos Tropicales",                            "ALIMENTACION", "ALIMENTO", "PEZ",     10700,  1, "/productos/5.png"),
  new Producto(6, "ReptilSnack Insectos Deshidratados",                     "ALIMENTACION", "ALIMENTO", "REPTIL",   9500,  0, "/productos/6.png"),
  new Producto(7, "CanineCrunch Bocadillos de Pollo",                       "ALIMENTACION", "ALIMENTO", "PERRO",   70200, 30, "/productos/7.png"),
  new Producto(8, "MiauMix Croquetas de Atún",                              "ALIMENTACION", "ALIMENTO", "GATO",    10500,  9, "/productos/8.png"),
  new Producto(9, "HealthyHerbivore Hierbas para Conejos",                  "ALIMENTACION", "ALIMENTO", "ROEDOR",  18500,  8, "/productos/9.png"),
  new Producto(10, "PawsLick Láminas de Salmón Liofilizado",                "ALIMENTACION", "ALIMENTO", "GATO",    13500,  3, "/productos/10.png")
];

